services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: mywebapp
      POSTGRES_PASSWORD: mywebapp_pass
      POSTGRES_DB: mywebapp
    ports:
      - "5433:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./deploy/config/config.yaml:/etc/mywebapp/config.yaml:ro
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mywebapp
      SERVER_ADDRESS: 0.0.0.0
    depends_on:
      - db
